version: '3.8'

services:
  icecast:
    build: ./icecast
    ports:
      - "8000:8000"
    
  liquidsoap:
    image: pltnk/liquidsoap
    volumes:
      - ./liquidsoap/music:/music
      - ./liquidsoap/script.liq:/etc/liquidsoap/script.liq
    depends_on:
      - icecast
    environment:
      - ICECAST_SOURCE_PASSWORD=${ICECAST_SOURCE_PASSWORD}

  api:
    build: ./api
    ports:
      - "8001:8000"
    environment:
      - ICECAST_URL=http://icecast:8000
    depends_on:
      - icecast
