apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-tls-prod
spec:
  secretName: web-tls-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - tsoum-radio.duckdns.org