apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-tls-staging
spec:
  secretName: web-tls-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - tsoum-radio.duckdns.org