apiVersion: batch/v1
kind: CronJob
metadata:
  name: dj-ia
spec:
  schedule: "0 */2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: dj-ia
              image: ghcr.io/henintsoaraj/lava-sofina-dj-ia:14dfcc1222e2880a9df4285e8ac02dd8a06bc151
              env:
                - name: GEMINI_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: gemini-api-key
                      key: GEMINI_API_KEY

                - name: CHEMIN_DE_SORTIE
                  value: /tmp/dj-audio/

              
              volumeMounts:
                - name: dj-audio-storage
                  mountPath: /tmp/dj-audio
          volumes:
            - name: dj-audio-storage
              persistentVolumeClaim:
                claimName: dj-audio-storage

          restartPolicy: Never
      backoffLimit: 1