name: Build Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: Generate icecast.xml for secret
        run: sed 's/xxxxxx/${{ secrets.ICECAST_SOURCE_PASSWORD }}/' icecast/icecast.xml.example > icecast/icecast.xml

    
      - name: Build Icecast Image
        run: cd icecast/ && docker build -t icecast .
